app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('catering/', views.catering, name='catering'),

    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-password/', views.verify_password, name='verify_password'),

    path('menu/', views.menu, name='menu'),
    path('takeaway/', views.takeaway, name='takeaway'),
    path('delivery/', views.delivery, name='delivery'),
    path('user-ajax-addtocart/', views.user_ajax_addtocart, name='user_ajax_addtocart'),


    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.sign_out, name='sign_out'),

    path('user-admin/', views.user_admin, name='user_admin'),
    path('user-admin-address-active/', views.user_admin_address_active, name='user_admin_address_active'),

    path('admin-logout/', views.admin_sign_out, name='admin_sign_out'),
    path('profile-update/', views.profile_update, name='profile_update'),
    path('address-update/', views.address_update, name='address_update'),
    path('address-delete/<int:id>/', views.address_delete, name='address_delete'),
    path('user-ajax-address-edit/', views.user_ajax_address_edit, name='user_ajax_address_edit'),
    path('user-edit-address-update/', views.user_edit_address_update, name='user_edit_address_update'),

    path('subscription/', views.subscription, name='subscription'),
    path('subscription-details/<str:id>/', views.subscription_details, name='subscription_details'),
    path('subscription-update/', views.subscription_update, name='subscription_update'),


    path('order/', views.order, name='order'),
    path('admin-ajax-order/', views.admin_ajax_order, name='admin_ajax_order'),
    path('order-details/<int:id>/', views.order_details, name='order_details'),
    path('admin-ajax-order-subscription/', views.admin_ajax_order_subscription, name='admin_ajax_order_subscription'),

    path('driver/', views.driver1, name='driver1'),
    path('admin-orders-payment/<int:id>/', views.admin_orders_payment, name='admin_orders_payment'),
    path('driver-orders-completed/<int:id>/', views.driver_orders_completed, name='driver_orders_completed'),
    path('driver-orders-decline/<int:id>/', views.driver_orders_decline, name='driver_orders_decline'),

    #admin
    path('admin-index/', views.admin_index, name='admin_index'),

    path('admin-categories/', views.admin_categories, name='admin_categories'),
    path('admin-categories-edit/', views.admin_categories_edit, name='admin_categories_edit'),
    path('admin-categories-edit-value/', views.admin_categories_ed, name='admin_categories_ed'),
    path('admin-categories-delete/<int:id>/', views.admin_categories_delete, name='admin_categories_delete'),

    path('admin-items/', views.admin_items, name='admin_items'),
    path('admin-item-ajax-edit/', views.admin_item_ajax_edit, name='admin_item_ajax_edit'),
    path('admin-item-edit/', views.admin_item_edit, name='admin_item_edit'),
    path('admin-items-delete/<int:id>/', views.admin_items_delete, name='admin_items_delete'),

    path('admin-meals/', views.admin_meals, name='admin_meals'),
    path('admin-meals-edit/<int:id>/', views.admin_meals_edit, name='admin_meals_edit'),
    path('admin-get-items/', views.admin_ajax_get_items, name='admin_ajax_get_items'),
    path('admin-meals-delete/<int:id>/', views.admin_meals_delete, name='admin_meals_delete'),
    path('admin-meals-update-special/', views.admin_meals_update_special, name='admin_meals_update_special'),


    path('admin-orders/', views.admin_orders, name='admin_orders'),
    path('admin-ajax-order-make-paid/', views.admin_orders_ajax_order_make_paid, name='admin_orders_ajax_order_make_paid'),


    path('admin-orders-delete/<int:id>/', views.admin_orders_delete, name='admin_orders_delete'),
    path('admin-orders-delivered/<int:id>/', views.admin_orders_delivered, name='admin_orders_delivered'),
    path('admin-orders-edit/<int:id>/', views.admin_orders_edit, name='admin_orders_edit'),
    path('admin-orders-decline/<int:id>/', views.admin_orders_decline, name='admin_orders_decline'),
    path('admin-orders-refund/<int:id>/', views.admin_orders_refund, name='admin_orders_refund'),


    path('admin-todayreport/', views.admin_todayreport, name='admin_todayreport'),
    path('admin-daliyorder/', views.admin_dailyorder, name='admin_dailyorder'),

    path('admin-takeaway-close-time/', views.admin_takeaway_close_time, name='admin_takeaway_close_time'),

    path('admin-suburb/', views.admin_suburb, name='admin_suburb'),
    path('admin-suburb-edit/<int:id>/', views.admin_suburb_edit, name='admin_suburb_edit'),
    path('admin-suburb-delete/<int:id>/', views.admin_suburb_delete, name='admin_suburb_delete'),
    path('admin-add-suburb/', views.admin_add_suburb, name='admin_add_suburb'),


    path('admin-drivers/', views.admin_drivers, name='admin_drivers'),
    path('admin-driver-ajax-edit/', views.admin_driver_ajax_edit, name='admin_driver_ajax_edit'),
    path('admin-driver-edit/', views.admin_driver_edit, name='admin_driver_edit'),
    path('admin-drivers-delete/<int:id>/', views.admin_driver_delete, name='admin_driver_delete'),


    path('admin-deliverytifin/', views.admin_deliverytifin, name='admin_deliverytifin'),
    path('admin-driver-orders/<int:id>/', views.admin_order_details_1, name='admin_order_details_1'),


    path('admin-customers/', views.admin_customers, name='admin_customers'),
    path('admin-customers-profile/<int:id>/', views.admin_customers_profile, name='admin_customers_profile'),
    path('admin-customers-password/<int:id>/', views.admin_customers_password, name='admin_customers_password'),
    path('admin-customers-orders-details/<int:id>/', views.admin_customers_orders_details, name='admin_customers_orders_details'),

    path('admin-user-active/', views.admin_user_update_special, name='admin_user_update_special'),
    path('admin-get-user/', views.admin_ajax_get_user, name='admin_ajax_get_user'),
    path('admin-customer-dashboard/', views.admin_customer_dashboard, name='admin_customer_dashboard'),


    path('admin-balance-edit/<int:id>/', views.admin_bal_edit, name='admin_bal_edit'),
    path('admin-balance-delete/<int:id>/', views.admin_bal_delete, name='admin_bal_delete'),
    path('admin-balance-ajax-edit/', views.admin_ajax_balance_edit, name='admin_ajax_balance_edit'),

    path('admin-note-edit/<int:id>/', views.admin_note_edit, name='admin_note_edit'),
    path('admin-note-delete/<int:id>/', views.admin_note_delete, name='admin_note_delete'),
    path('admin-note-ajax-edit/', views.admin_ajax_note_edit, name='admin_ajax_note_edit'),

    path('admin-customers-balance/<int:id>/', views.admin_customers_balance, name='admin_customers_balance'),
    path('admin-customers-note/<int:id>/', views.admin_customers_note, name='admin_customers_note'),


    path('admin-users/', views.admin_users, name='admin_users'),
    path('admin-add-users/', views.admin_add_users, name='admin_add_users'),

    path('admin-sizes/', views.admin_sizes, name='admin_sizes'),
    path('admin-sizes-delete/<int:id>/', views.admin_sizes_delete, name='admin_sizes_delete'),

    path('admin-variations/', views.admin_variations, name='admin_variations'),
    path('admin-variations-ajax-edit/', views.admin_ajax_variations_edit, name='admin_ajax_variations_edit'),
    path('admin-variations-edit-value/', views.admin_variations_edit, name='admin_variations_edit'),
    path('admin-variations-delete/<int:id>/', views.admin_variations_delete, name='admin_variations_delete'),

    path('admin-subscription/', views.admin_subscription, name='admin_subscription'),
    path('admin-subscription-plans/', views.admin_subscription_plans, name='admin_subscription_plans'),

    path('admin-catering-menu/', views.admin_catering_menu, name='admin_catering_menu'),

    path('admin-promocode/', views.admin_promocode, name='admin_promocode'),
    path('admin-promocode-ajax-edit/', views.admin_ajax_promocode_edit, name='admin_ajax_promocode_edit'),
    path('admin-promocode-edit/', views.admin_promocode_edit, name='admin_promocode_edit'),
    path('admin-promocode-completed/<int:id>/', views.admin_promocode_completed, name='admin_promocode_completed'),
    path('admin-promocode-delete/<int:id>/', views.admin_promocode_delete, name='admin_promocode_delete'),

    path('admin-user-subscription-details/', views.admin_user_subscription_details, name='admin_user_subscription_details'),
    path('admin-login/', views.admin_login, name='admin_login'),

    path('admin-salesreport/', views.admin_salesreport, name='admin_salesreport'),
    path('admin-orderreport/', views.admin_orderreport, name='admin_orderreport'),
    path('admin-itemreport/', views.admin_itemreport, name='admin_itemreport'),
    path('admin-subrreport/', views.admin_suburreport, name='admin_suburreport'),

    path('admin-timing/', views.admin_timing, name='admin_timing'),
    path('admin-subrreport/', views.admin_closedate, name='admin_closedate'),

    # footer links
    path('terms-conditions/', views.terms_conditions, name='terms_conditions'),
    path('refund-policy/', views.refund_policy, name='refund_policy'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('indian-tiffin-service-springvale-noble-park/', views.indian_tiffin_service_springvale_noble_park, name='indian_tiffin_service_springvale_noble_park'),
    path('indian-tiffin-service-mount-waverley/', views.indian_tiffin_service_mount_waverley, name='indian_tiffin_service_mount_waverley'),

tasteohome/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/templates/about.html
{% extends 'base.html' %}
{% block title %}Taste Of Home | About Us{% endblock %}
{% block nav %}

      {% if cookies.get_name == None or cookies.get_name == "" %}
        <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link" href="{% url 'app:index' %}">Home</a></li>
          <li><a class="nav-link active" href="{% url 'app:about' %}">About</a></li>
<!--          <li><a class="nav-link" href="{% url 'app:menu' %}">Menu</a></li>-->
          <li><a class="nav-link" href="{% url 'app:catering' %}">Catering Menu</a></li>
          <li><a class="nav-link" href="{% url 'app:contact' %}">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
        <a href="{% url 'app:login' %}" class="book-a-table-btn scrollto">Login</a>
      {% else %}
          <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
              <li><a class="nav-link" href="{% url 'app:index' %}">Home</a></li>
              <li><a class="nav-link active" href="{% url 'app:about' %}">About</a></li>
              <li><a class="nav-link" href="{% url 'app:menu' %}">Menu</a></li>
              <li><a class="nav-link" href="{% url 'app:catering' %}">Catering Menu</a></li>
              <li><a class="nav-link" href="{% url 'app:contact' %}">Contact</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav>
         <div class="dropdown p-2">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        {{cookies.get_name}}
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'app:user_admin' %}">Dashboard</a>
          <a class="dropdown-item" href="{% url 'app:sign_out' %}">Logout</a>
        </div>
      </div>
      {% endif %}
{% endblock %}
{% block head %}About Us{% endblock %}
{% block htmlbody %}
   <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container-fluid">

        <div class="row">
          <div class="col-lg-7 d-flex flex-column justify-content-center align-items-stretch">
            <div class="content">
              <h2>ABOUT <strong> TASTE OF HOME</strong></h2>
              <p>
               Taste Of Home is your local Indian tiffin delivery service in Melbourne serving the best tiffin to students and workers who have little to no time for preparing their food. We deliver a personalised eating experience from the comfort of your home with our daily and monthly tiffin delivery subscription.
              </p>
              <p>
                Cooked with love and care, every dish on our tiffin menu is cooked perfectly with quality ingredients and local produce. We never compromise with health and hygiene. Every tiffin is packed to perfection with home cooked recipes.Cooked with love and care, every dish on our tiffin menu is cooked perfectly with quality ingredients and local produce. We never compromise with health and hygiene. Every tiffin is packed to perfection with home cooked recipes.
              </p>
              <p>
                Our chef very well knows that not everybody has the time to prepare tasty food, that is why we strive to deliver a healthy tiffin on time, no matter what time of the day or night it is. Whether you have love for a vegetarian meal or prefer a non-vegetarian tiffin, we serve everything you love to eat without any repetition of dishes for the entire week.
              </p>
              <p>
                For the best Indian tiffin delivery in Melbourne and surroundings, feel free to place an order with Taste Of Home. Give us a call today or visit our facility. Doorstep delivery and pickup service available.
              </p>
            </div>

          </div>
          <div class="col-lg-5 align-items-stretch" style="background-image: url('../static/img/about.jpg');">
            
          </div>


        </div>

      </div>
    </section><!-- End About Section -->

 {% endblock %}

app/templates/menu.html
{% extends 'base.html' %}
{% block title %}Taste Of Home | Menu{% endblock %}
{% block nav %}
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link" href="{% url 'app:index' %}">Home</a></li>
          <li><a class="nav-link" href="{% url 'app:about' %}">About</a></li>
          <li><a class="nav-link active" href="{% url 'app:menu' %}">Menu</a></li>
            <li><a class="nav-link" href="{% url 'app:subscription' %}">Subscription</a></li>
          <li><a class="nav-link" href="{% url 'app:catering' %}">Catering Menu</a></li>
          <li><a class="nav-link" href="{% url 'app:contact' %}">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      {% if cookies.get_name == None or cookies.get_name == "" %}
        {% if get_email == "test"%}
            <a href="{% url 'app:login' %}" class="book-a-table-btn scrollto">Login</a>
        {% else%}
        <div class="dropdown p-2">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            {{get_email}}
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'app:user_admin' %}">Dashboard</a>
              <a class="dropdown-item" href="{% url 'app:sign_out' %}">Logout</a>
            </div>
          </div>

        {% endif %}
      {% else %}
         <div class="dropdown p-2">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        {{cookies.get_name}}
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'app:user_admin' %}">Dashboard</a>
          <a class="dropdown-item" href="{% url 'app:sign_out' %}">Logout</a>
        </div>
      </div>
      {% endif %}
{% endblock %}
{% block head %}Menu{% endblock %}
{% block htmlbody %}
   <!-- ======= Menu ======= -->
    <div class="container">
      <div class="row mb-4">
        <div class="col-sm-12 col-md-12 col-lg-4 col-xs-12"></div>
        <div class="col-sm-12 col-md-12 col-lg-4 col-xs-12">
          <h4 class="badge-pill badge-green mt-3 mb-3 p-2 text-center">Choose Order Type</h4>
              <a href="{% url 'app:delivery' %}" class="badge-pill alink delivery"><i class="bx bxs-truck"></i>&nbsp;Home Delivery</a>
              <a href="{% url 'app:takeaway' %}" class="badge-pill alink takeaway"><i class="bx bx-restaurant"></i>&nbsp;Take Away</a>

        </div>
        <div class="col-sm-12 col-md-12 col-lg-4 col-xs-12"></div>
      </div>
    </div>
    <!-- Menu -->

</div>
{% endblock %}

app/templates/order-details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Taste Of Home | Order Info</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script>
  <script src="https://cdn.datatables.net/fixedheader/3.4.0/js/dataTables.fixedHeader.min.js"></script>
  <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/fixedheader/3.4.0/css/fixedHeader.bootstrap4.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body>
  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center fixed-top topbar-transparent">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-center justify-content-lg-start">
      <i class="bi bi-phone d-flex align-items-center"><span>+61 417 923 930</span></i>
      <i class="bi bi-clock ms-4 d-none d-lg-flex align-items-center"><span>Open: 12:05 AM - 06:00 PM</span></i>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <div class="logo me-auto">
        <!-- <h1><a href="index.html">Taste of Home</a></h1> -->
        
         <a href="{% url 'app:index' %}"><img src="{% static 'img/logo.png' %}" alt="" class="img-fluid"></a>
      </div>

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link" href="{% url 'app:index' %}">Home</a></li>
          <li><a class="nav-link" href="{% url 'app:about' %}">About</a></li>
          <li><a class="nav-link" href="{% url 'app:menu' %}">Menu</a></li>
          <li><a class="nav-link" href="{% url 'app:subscription' %}">Subscription</a></li>
          <li><a class="nav-link " href="{% url 'app:catering' %}">Catering Menu</a></li>
          <li><a class="nav-link" href="{% url 'app:contact' %}">Contact</a></li>

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      {% if cookies.get_name == None or cookies.get_name == "" %}
        {% if get_email == "test"%}
            <a href="{% url 'app:login' %}" class="book-a-table-btn scrollto">Login</a>
        {% else%}
        <div class="dropdown p-2">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            {{get_email}}
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'app:user_admin' %}">Dashboard</a>
              <a class="dropdown-item" href="{% url 'app:sign_out' %}">Logout</a>
            </div>
          </div>

        {% endif %}
      {% else %}
         <div class="dropdown p-2">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        {{cookies.get_name}}
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'app:user_admin' %}">Dashboard</a>
          <a class="dropdown-item" href="{% url 'app:sign_out' %}">Logout</a>
        </div>
      </div>
      {% endif %}
    </div>
  </header>
 <section id="aboutus" class="aboutus">
  <div class="container position-relative">
      <div class="row">
        <h1 class="section-header">Order Details</h1>
      
    </div>
  </section><!-- End Hero -->
   <!-- ======= Menu ======= -->
  <div class="container mt-2">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="d-flex flex-row border rounded mt-2 mb-2">
          <div class="row">
            <div class="row suborderdet1">
              <div class="col-md-6 form-group">
                  <label for="ordernumber">Order Number:</label>
                  <span class="customer-name">{{order_data.order_id}}</span>
              </div>
              <div class="col-md-6 form-group">
                  <label for="datetime">Ordered Date/Time:</label>
                  <span>{{order_data.order_date}}</span>
              </div>
            </div>
            <div class="row suborderdet1">
              <div class="col-md-6 form-group">
                <label for="address">Address:</label>
                <span>{{order_data.order_address}}</span>
              </div>
              <div class="col-md-6 form-group">
                <label for="datentime">Delivery Status:</label>
                <span class="status">{{order_data.order_status}}</span>
              </div>
            </div>
            <div class="row suborderdet1">
              <div class="col-md-6 form-group">
                <label for="address">Delivery Type:</label>
                <span>{{order_data.order_type}}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
  <div class="container card shadow justify-content-center mt-2 mb-3">
    <div class="flex-row border rounded mt-2 mb-2">
      <div class="table-responsive-sm mt-2 mb-2">
        <table id="example6" class="table table-bordered table-striped" style="width:100%">
          <thead>
            <tr>
              <th>SNo</th>
              <th>Meal Name</th>
              <th>Items</th>
              <th>Price</th>
              <th>Quantity</th>
              <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order_data.meals_date.meal_text}}</td>
                <td>{{order_data.items}}</td>
                <td>{{order_data.meals_date.price}}</td>
                <td>{{order_data.meals_date.qty}}</td>
                <td>{{price_list.total}}</td>
            </tr>
             <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="orderfont">Total:</td>
                <td>{{price_list.total}}</td>
            </tr>
             <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="orderfont">Delivery Price:</td>
                <td>{{order_data.meals_date.delivery_price}}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="orderfont">Discount Price:</td>
                <td>{{order_data.order_discount_price}}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="orderfont">Grand Total:</td>
                <td>{{price_list.grand_total}}</td>
            </tr>
        </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="logo me-auto col-lg-4">
          <h4>Taste of Home</h4>
          <a href="index.html"><img src="{% static 'img/logo.png' %}" alt="Taste of Home" class="img-fluid" width="40%"></a>
          <div class="social-links">
            <a href="https://www.facebook.com/TOHMelb/" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="https://www.instagram.com/tasteofhomemelb/" class="instagram"><i class="bx bxl-instagram"></i></a>
          </div>
        </div>
        <div class="col-lg-4">
          <h4>Areas We Serve</h4>
          <ul>
            <li><a href="{% url 'app:indian_tiffin_service_melbourne' %}">Melbourne</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_springvale_noble_park' %}">Springvale & Noble Park</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_dandenong' %}">Dandenong</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_cranbourne' %}">Cranbourne</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_hampton_park' %}">Hampton Park</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_mount_waverley' %}">Mount Waverley</a></li>
            <li><a href="{% url 'app:indian_tiffin_service_clayton_keysborough' %}">Clayton & Keysborough</a></li>
          </ul>
        </div>
        <div class="col-lg-4">
          <h4>More Links</h4>
          <ul>
            <li><a href="{% url 'app:index' %}">Home</a></li>
            <li><a href="{% url 'app:about' %}">About</a></li>
            <li><a href="{% url 'app:contact' %}">Contact</a></li>
            <li><a href="{% url 'app:privacy_policy' %}">Privacy Policy</a></li>
            <li><a href="{% url 'app:terms_conditions' %}">Terms & Conditions</a></li>
            <li><a href="{% url 'app:refund_policy' %}">Refund Policy</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="copyright credits">
          &copy; Copyright <strong><span>Taste of Home</span></strong>. All Rights Reserved | Designed and Developed By <a href="https://kreativdigimarketing.com/">Kreativ Digi Marketing</a>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/main-login.js' %}"></script>
  <script type="text/javascript">
    new DataTable('#example6', {
    fixedHeader: true
    });
  </script>
</body>
</html>